#!/usr/bin/env tsx
/**
 * Bundles the stdio MCP server into one self-contained dist/server.js.
 *
 * `.mcp.json` starts `node ${CLAUDE_PLUGIN_ROOT}/dist/server.js`, and a
 * marketplace install is plugin/ as committed: no node_modules, and no
 * install or build step. tsc's server.js imports @modelcontextprotocol/sdk and
 * zod by package name, so a GitHub install died on start with
 * ERR_MODULE_NOT_FOUND and Claude Code showed "Failed to reconnect to plugin:
 * CONNECTION_CLOSED" (STEP-3155). The bundle carries those packages inline and
 * imports nothing but node: built-ins.
 *
 * `npm run build` runs this after tsc, so it replaces tsc's server.js and
 * leaves the rest of dist/ as tsc wrote it. The repo is public and the bundle
 * redistributes the packages, so their licence texts ship beside it in
 * dist/server.js.LICENSE.txt.
 *
 * The sync test in src/__tests__/server-bundle.test.ts bundles in memory and
 * compares both files with the committed ones.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { build } from "esbuild"

export const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
export const SERVER_PATH = join(PLUGIN_ROOT, "dist", "server.js")
export const LICENSE_PATH = `${SERVER_PATH}.LICENSE.txt`

export async function bundleServer(): Promise<{ server: string; licenses: string }> {
  const result = await build({
    absWorkingDir: PLUGIN_ROOT,
    entryPoints: ["src/server.ts"],
    outfile: SERVER_PATH,
    bundle: true,
    platform: "node",
    format: "esm",
    // plugin/README.md: Node.js 20+
    target: "node20",
    banner: {
      js: "// Generated by scripts/bundle-server.ts (npm run build): src/server.ts and every package it imports. Licences: server.js.LICENSE.txt",
    },
    metafile: true,
    write: false,
    logLevel: "warning",
  })

  // An input's package is the directory after its last node_modules/, with
  // its scope: node_modules/@modelcontextprotocol/sdk/dist/esm/types.js is
  // node_modules/@modelcontextprotocol/sdk.
  const packageDirs = new Set<string>()
  for (const input of Object.keys(result.metafile.inputs)) {
    const at = input.lastIndexOf("node_modules/")
    if (at === -1) continue
    const [first, second] = input.slice(at + "node_modules/".length).split("/")
    packageDirs.add(input.slice(0, at) + "node_modules/" + (first.startsWith("@") ? `${first}/${second}` : first))
  }

  const sections = [...packageDirs].sort().map((dir) => {
    const root = join(PLUGIN_ROOT, dir)
    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { name: string; version: string; license?: string }
    const file = readdirSync(root).sort().find((name) => /^licen[cs]e(\.|$)/i.test(name))
    if (!file) {
      throw new Error(`${pkg.name} is bundled into dist/server.js but ships no LICENSE file to put beside it`)
    }
    return `${pkg.name}@${pkg.version} (${pkg.license ?? "no license field"})\n\n${readFileSync(join(root, file), "utf8").trim()}\n`
  })

  return {
    server: result.outputFiles[0].text,
    licenses: `dist/server.js bundles the packages below. Each one's licence follows its name.\n\n${sections.join(`\n${"-".repeat(72)}\n\n`)}`,
  }
}

if (process.argv[1]?.endsWith("bundle-server.ts")) {
  const { server, licenses } = await bundleServer()
  writeFileSync(SERVER_PATH, server)
  writeFileSync(LICENSE_PATH, licenses)
}
